### PR TITLE
Spare

### PR DESCRIPTION
**Pull request by StrawberryDelite**

### CODE REVIEW

**Comment by happydance** [comment]
Do they look okay?  Also I'm not sure what to do about the href address
part.... :(

**Comment by StrawberryDelite** [comment]
https://hopper.csustan.edu/~PSantos/

**Comment by StrawberryDelite** [comment]
Unfortunately I'm getting kicked out of the lab in 10 minutes, so no time
left to fix anything; I'm having trouble with the ad hoc query as well, haha

Sorry I ended up getting started on this so late

**Comment by happydance** [comment]
It's okay!  I'm happy that we got this far   :)

**Comment by happydance** [comment]
I think I made the changes to the file names on the spare copy instead of
the master copy on github.  Could that be why the second group of queries
(the ones where I did the php part?) don't work?  Or does it just not like
my sql.... which worked fine on the db itself.....

**Comment by StrawberryDelite** [comment]
I merged the two c:

I thought I gave you admin permission but apparently I didn't. The way it
works is you fork it into a different branch, then someone has to review it
and then merge it into the main one. It lets multiple people work on the
same project at once, tag different parts of the code as "this person did
this", and for open source projects, allows for strangers to contribute to
code while still having oversight

**Comment by happydance** [comment]
You did merge the two the first time.  It's just that I changed the address
thing after that from like this (on the master)

li><a href="http://www.cs.csustan.edu/">Query1</a>: &lt;Find the best
burgers by burger rating&gt;.

to this:

li><a href="http://hopper.csustan.edu/~PSantos/Bestburger.php">Bestburger</a>:
&lt;Find the best burgers by burger rating&gt;.

All 5 of them are different on the spare copy.  I tested the link that was
in Ms. Thomas's email and all 5 of mine don't work even though I used the
same php as yours, only the sql part is changed.   I'm hoping it's just
that the file didn't get updated.   :)

On Fri, May 20, 2016 at 11:05 PM, StrawberryDelite <notifications@github.com
> wrote:

> I merged the two c:
>
> I thought I gave you admin permission but apparently I didn't. The way it
> works is you fork it into a different branch, then someone has to review it
> and then merge it into the main one. It lets multiple people work on the
> same project at once, tag different parts of the code as "this person did
> this", and for open source projects, allows for strangers to contribute to
> code while still having oversight
>

**Pull request merged**
